### ISSUE TITLE
New Apache version

### ISSUE THREAD

**Issue by Craeckie** [GrahamDumpleton/mod_wsgi-docker#12]
There's a new version at http://mirror.ventraip.net.au/apache/httpd/ and the old one is not present anymore.
New version: 2.4.23

I can make a pull request once it compiled successfully.

**Comment by GrahamDumpleton** [comment]
Docker images on Docker Hub updated with latest Apache httpd, as well as latest versions of nghttp2, tini and mod_wsgi-express.
