### ISSUE TITLE
Django Demo example.wsgi 

### ISSUE THREAD

**Issue by 0x3bfc** [GrahamDumpleton/mod_wsgi-docker#2]
Hi Mr. Graham, 

I did not find example.wsgi in Django Demo where you call in your mod_wsgi args in Dockerfile, can you push it to the repo.

regards,
Ahmed

**Comment by GrahamDumpleton** [comment]
The string 'example.wsgi' is a module path, not the name of a file. You should replace 'example' with the name of your project. The module path would then map to the file path of 'example/wsgi.py', where again, 'example' is replaced with the name of your project.

In other words, it should map to the 'wsgi.py' file found in the same directory as your 'settings.py' file, both of which would have been generated by the Django 'startproject' management command.

Take for example where my project was called 'mysite' and so I had:

```
$ ls -las manage.py mysite/*.py
8 -rw-r--r--  1 graham  staff   249 16 Mar  2014 manage.py
0 -rw-r--r--  1 graham  staff     0 16 Mar  2014 mysite/__init__.py
8 -rw-r--r--  1 graham  staff  2997  8 Aug  2014 mysite/settings.py
8 -rw-r--r--  1 graham  staff   522 17 Jun  2014 mysite/urls.py
8 -rw-r--r--  1 graham  staff   908 30 Oct  2014 mysite/views.py
8 -rw-r--r--  1 graham  staff   387 16 Mar  2014 mysite/wsgi.py
```

I would actually use the module path 'mysite.wsgi', which would map to 'mysite/wsgi.py'.

**Comment by 0x3bfc** [comment]
Thanks Graham. Actually, I was going to inform to make this issue closed but you preceded me by your answer,  I did this and I found what you said is true, sorry for this disturbance
